name: Feature - Infra
on:
  push:
    paths:
      - "infra/**"
      - "scripts/**"
      - ".github/**"
    branches-ignore:
      - main
jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Infrastructure Changes
        run: |
          ./scripts/infra-deploy.sh

  deploy-prod:
    name: Deploy Prod
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          ./scripts/infra-deploy.sh
